# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RH4l9HHcnAjx2LxqOSe7Y7qoWKb_QwzM
"""

#excelのURLリストからタイトルを取得する
import pandas as pd
import requests
from bs4 import BeautifulSoup
import csv

#urlリストを取得する
def get_excel_url(path):
  df = pd.read_excel(path) #excelデータを読み込む
  urlList = df['URL']
  return urlList

#URLからタイトルを抽出する
def get_site_title(urlList):
  title_link_list = []
  url_link_list =[]
  title_list = []
  
  for row in range(len(urlList)):
    target_url = urlList[row] #urlを一つずつ抽出
    
    #print(target_url)
    r = requests.get(target_url)
    soup = BeautifulSoup(r.content, "html.parser")
    
    #検索結果タイトルを抽出>
    tmp_result = soup.select(".r > a")
    
    for i in range(len(tmp_result)):
      url_text = tmp_result[i].get('href').replace('/url?q=','')
      title_text = tmp_result[i].get_text()
    
    url_link_list.append(url_text)
    title_list.append(title_text)
    #print(title_list)
  
  title_link_list = [title_list, url_link_list]
  return title_list,url_link_list

#タイトルを新規作成したexcelファイルに書き込む
def set_excel_url(title , url):
  with open("search_title_list.csv",'w',encoding='utf-8') as outcsv:
    csvwriter = csv.writer(outcsv)
    csvwriter.writerow(['タイトル','URL'])
    csvwriter.writerow([title,url])
    outcsv.close()
  
  
urlList = get_excel_url("test_data.xlsx")
#print(get_site_title(urlList))
(title,url) = get_site_title(urlList)
set_excel_url(title, url)